### ISSUE TITLE
subract function error?

### ISSUE THREAD

**Issue by ulvitalas** [ulvitalas/CodeRefinery_travis_ut#1]
$ pytest --verbose example.py
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /home/travis/virtualenv/python3.6.3/bin/python
cachedir: .cache
rootdir: /home/travis/build/ulvitalas/CodeRefinery_travis_ut, inifile:
collected 2 items                                                              
example.py::test_add PASSED                                              [ 50%]
example.py::test_subtract FAILED                                         [100%]
=================================== FAILURES ===================================
________________________________ test_subtract _________________________________
    def test_subtract():
>       assert subtract(2, 3) == -1
E       assert 5 == -1
E        +  where 5 = subtract(2, 3)
example.py:16: AssertionError
====================== 1 failed, 1 passed in 0.04 seconds ======================
The command "pytest --verbose example.py" exited with 1.

**Comment by ulvitalas** [comment]
subtract function failure

**Comment by maitraag** [comment]
I'll try to fix (in my own fork).
